version: '3.8'

services:
  web:
    build: .
    container_name: devops-web-app
    ports:
      - "8000:8000"
    restart: always

  redis-db:
    image: redis:alpine
    container_name: devops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
